import { CheckCircleIcon, Edit2Icon, PlusIcon, TrashIcon } from '@assets/icons';
import Breadcrumb from '@components/breadcrumb';
import Divider from '@components/common/Divider';
import Layout from '@components/common/Layout';
import SideBar from '@components/common/user/SideBar';
import { isEmpty } from 'lodash';
import { NextPage } from 'next';
import Head from 'next/head';
import { ChangeEvent, useState } from 'react';
import { default as Input } from '@components/common/auth/AuthInput';
import Button from '@components/common/Button';

const add = [
  {
    id: '1',
    name: 'TRẦN NGUYÊN TÀI',
    address:
      '10/9 đường 11,........, Phường Bình Thọ, Quận Thủ Đức, Hồ Chí Minh',
    phone: '0979779284',
    is_default: true
  },
  {
    id: '2',
    name: 'TRẦN NGUYÊN TÀI',
    address:
      '10/9 đường 11,........, Phường Bình Thọ, Quận Thủ Đức, Hồ Chí Minh',
    phone: '0979779284',
    is_default: false
  }
];
type Props = any;
const CreateAddressPage: NextPage<Props> = () => {
  const [address, setAddress] = useState<{
    id: string;
    name: string;
    address: string;
    phone: string;
    is_default: boolean;
  }>({
    id: '',
    name: '',
    address: '',
    phone: '',
    is_default: false
  });
  const onChange = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setAddress({
      ...address,
      [e.target.name]: value
    });
  };
  return (
    <Layout>
      <Head>
        <title>Địa chỉ của tôi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center overflow-auto h-main bg-main">
        <div className="max-w-screen-xl w-full px-4">
          <div className="p-4 justify-center flex-col flex gap-x-4">
            <Breadcrumb
              breadcrumbs={[
                { value: 'Trang chủ', href: '/dien-thoai' },
                { value: 'Địa chỉ của tôi', href: '/address' }
              ]}
            />
            <Divider className="mt-0 mb-4" />
          </div>
          <div className="flex">
            <SideBar />
            <div className="flex-1">
              <div className="text-2xl font-light mt-1 mb-4">
                Tạo mới địa chỉ
              </div>
              <div className="rounded bg-white py-9 px-6">
                <form className="flex space-x-8">
                  <div className="flex-1">
                    <div className="flex items-center mb-5">
                      <label
                        htmlFor="name"
                        className="text-base mr-4 text-[#333333] min-w-[110px] w-[110px]"
                      >
                        Họ và tên:{' '}
                      </label>
                      <div className="flex-1">
                        <Input
                          id="name"
                          name="name"
                          value={address.name}
                          onChange={onChange}
                          inputClassName="!h-10 !mt-0"
                          placeholder="Nhập họ và tên"
                        />
                      </div>
                    </div>
                    <div className="flex items-center mb-5">
                      <label
                        htmlFor="phone"
                        className="text-base mr-4 text-[#333333] min-w-[110px] w-[110px]"
                      >
                        Số điện thoại:{' '}
                      </label>
                      <div className="flex-1">
                        <Input
                          id="phone"
                          name="phone"
                          value={address.phone}
                          onChange={onChange}
                          inputClassName="!h-10 !mt-0"
                          placeholder="Nhập số điện thoại"
                        />
                      </div>
                    </div>
                  </div>

                  <div className="flex-1">
                    <div className="flex items-center mb-5">
                      <label
                        htmlFor="province"
                        className="text-base mr-4 text-[#333333] min-w-[110px] w-[110px]"
                      >
                        Tỉnh/Thành phố:{' '}
                      </label>
                      <select
                        id="province"
                        className="px-4 h-10 mt-0 w-full block border  text-gray-900 rounded focus:outline-none border-gray-300 focus:border-primary"
                      >
                        <option selected>Chọn Tỉnh/ Thành phố</option>
                        <option value="US">United States</option>
                        <option value="CA">Canada</option>
                        <option value="FR">France</option>
                        <option value="DE">Germany</option>
                      </select>
                    </div>

                    <div className="flex items-center mb-5">
                      <label
                        htmlFor="district"
                        className="text-base mr-4 text-[#333333] min-w-[110px] w-[110px]"
                      >
                        Quận huyện:{' '}
                      </label>
                      <select
                        id="district"
                        className="px-4 h-10 mt-0 w-full block border  text-gray-900 rounded focus:outline-none border-gray-300 focus:border-primary"
                      >
                        <option selected>Chọn Quận huyện</option>
                        <option value="US">United States</option>
                        <option value="CA">Canada</option>
                        <option value="FR">France</option>
                        <option value="DE">Germany</option>
                      </select>
                    </div>

                    <div className="flex items-center mb-5">
                      <label
                        htmlFor="ward"
                        className="text-base mr-4 text-[#333333] min-w-[110px] w-[110px]"
                      >
                        Phường xã:{' '}
                      </label>
                      <select
                        id="ward"
                        className="px-4 h-10 mt-0 w-full block border  text-gray-900 rounded focus:outline-none border-gray-300 focus:border-primary"
                      >
                        <option selected>Chọn Phường xã</option>
                        <option value="US">United States</option>
                        <option value="CA">Canada</option>
                        <option value="FR">France</option>
                        <option value="DE">Germany</option>
                      </select>
                    </div>

                    <div className="flex items-center mb-5">
                      <label
                        htmlFor="address"
                        className="self-start text-base mr-4 text-[#333333] min-w-[110px] w-[110px]"
                      >
                        Địa chỉ:{' '}
                      </label>
                      <textarea
                        id="address"
                        rows={3}
                        className="block p-2.5 w-full text-gray-900 rounded border border-gray-300 focus:outline-none focus:border-primary"
                        placeholder="Nhập địa chỉ..."
                      ></textarea>
                    </div>
                    <div className="flex items-center mb-5">
                      <label className="self-start text-base mr-4 text-[#333333] min-w-[110px] w-[110px]">
                        &nbsp;
                      </label>
                      <div className="flex items-center select-none">
                        <input
                          id="default"
                          type="checkbox"
                          className="h-4 w-4 border-gray-300 rounded text-indigo-600 focus:ring-indigo-500 cursor-pointer"
                          // checked={value.includes(brand.value) ? true : false}
                          // onChange={() => dispatch(handleAction(brand.value))}
                        />
                        <label
                          htmlFor="default"
                          className="text-base ml-4 text-[#333333]"
                        >
                          Đặt làm địa chỉ mặc định
                        </label>
                      </div>
                    </div>
                  </div>
                </form>
                <Button className="ml-auto text-white flex items-center justify-center bg-primary py-1">
                  <PlusIcon className="mr-2" />
                  Thêm
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
};
export default CreateAddressPage;
