import { CheckCircleIcon, Edit2Icon, PlusIcon, TrashIcon } from '@assets/icons';
import Breadcrumb from '@components/breadcrumb';
import Divider from '@components/common/Divider';
import Layout from '@components/common/Layout';
import SideBar from '@components/common/user/SideBar';
import classNames from 'classnames';
import { isEmpty } from 'lodash';
import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import Tippy from '@tippyjs/react';
import Tooltip from '@components/common/Tooltip';

const add = [
  {
    id: '1',
    name: 'TRẦN NGUYÊN TÀI',
    address:
      '10/9 đường 11,........, Phường Bình Thọ, Quận Thủ Đức, Hồ Chí Minh',
    phone: '0979779284',
    is_default: true
  },
  {
    id: '2',
    name: 'TRẦN NGUYÊN TÀI',
    address:
      '10/9 đường 11,........, Phường Bình Thọ, Quận Thủ Đức, Hồ Chí Minh',
    phone: '0979779284',
    is_default: false
  }
];
type Props = any;
const AddressPage: NextPage<Props> = () => {
  const [address, setAddress] = useState(add);
  return (
    <Layout>
      <Head>
        <title>Địa chỉ của tôi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center overflow-auto h-main bg-main">
        <div className="max-w-screen-xl w-full px-4">
          <div className="p-4 justify-center flex-col flex gap-x-4">
            <Breadcrumb
              breadcrumbs={[
                { value: 'Trang chủ', href: '/dien-thoai' },
                { value: 'Địa chỉ của tôi', href: '/address' }
              ]}
            />
            <Divider className="mt-0 mb-4" />
          </div>
          <div className="flex">
            <SideBar active="address" />
            <div className="flex-1">
              <div className="text-2xl font-light mt-1 mb-4">
                Địa chỉ của tôi
              </div>
              <div>
                <Link href={'/user/address/create'}>
                  <a className="h-14 border-px border-dashed border-[#d8d8d8] mb-3 flex items-center justify-center bg-white text-base">
                    <PlusIcon className="mx-4 text-[#787878]" />
                    <span>Thêm địa chỉ mới</span>
                  </a>
                </Link>
                {!isEmpty(address) &&
                  address.map((item, _) => {
                    return (
                      <div
                        key={item.id}
                        className="bg-white rounded flex justify-between text-13 p-5 mb-3 last:mb-0"
                      >
                        <div>
                          <div className="uppercase mb-3 flex">
                            {item.name}
                            {item.is_default && (
                              <span className="flex items-center text-green-500 text-[12px] normal-case ml-5">
                                <CheckCircleIcon className="w-3.5 h-3.5 mr-2" />
                                <span>Địa chỉ mặc định</span>
                              </span>
                            )}
                          </div>
                          <div className="mb-2">
                            <span className="text-[#787878]">Địa chỉ: </span>
                            {item.address}
                          </div>
                          <div>
                            <span className="text-[#787878]">Điện thoại: </span>
                            {item.phone}
                          </div>
                        </div>
                        <div className="flex h-fit">
                          <Tippy
                            arrow={true}
                            content={<Tooltip text={'Chỉnh sửa'} />}
                            delay={100}
                          >
                            <span
                              className={classNames({
                                'mr-5': !item.is_default
                              })}
                            >
                              <Edit2Icon className="w-5 h-5 text-gray-500 cursor-pointer" />
                            </span>
                          </Tippy>
                          {!item.is_default && (
                            <>
                              <Tippy
                                arrow={true}
                                content={<Tooltip text={'Xoá'} />}
                                delay={100}
                              >
                                <span>
                                  <TrashIcon className="w-5 h-5 text-red-500 cursor-pointer" />
                                </span>
                              </Tippy>
                            </>
                          )}
                        </div>
                      </div>
                    );
                  })}
              </div>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
};
export default AddressPage;
