import Head from 'next/head';
import { NextPage, NextPageContext } from 'next';
import { Store } from '@app/store';
import { setSelectedProduct } from '@app/slice/homeSlice';
import Breadcrumb from '@components/breadcrumb';
import axiosClient from 'utils/api';
import ProductCarousel from '@components/carousel';
import { DetailProductType } from 'types';
import DeviceInfo from '@components/product-detail/DeviceInfo';
import Divider from '@components/common/Divider';
import MainInfo from '@components/product-detail/MainInfo';
import RatingAndCommentBox from '@components/product-detail/RatingAndCommentBox';
import QuestionBox from '@components/product-detail/QuestionBox';

type Props = {
  product: DetailProductType;
};

const Phone: NextPage<Props> = ({ product }) => {
  const { name, slug, attrs } = product;
  return (
    <>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center overflow-auto h-main">
        <div className="max-w-screen-xl w-full">
          <div className="py-4 px-10 justify-center flex-col flex gap-x-4">
            <Breadcrumb productName={name} slug={slug} />
            <Divider className="mt-0 mb-4" />
            <div className="flex">
              <div className="detail_product_left w-96">
                <div className="product-gallery">
                  <ProductCarousel
                    thumbnails={[
                      'https://image.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-12-pro-max_1__8.jpg',
                      'https://image.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-12-pro-max_4__8.jpg',
                      'https://image.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-12-pro-max_3__8.jpg',
                      'https://image.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-12-pro-max_2__8.jpg',
                      'https://image.cellphones.com.vn/358x/media/catalog/product/_/0/_0000_iphone-12-pro-max-nonlogo-5_1_2.jpg',
                      'https://image.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-12-pro-max_3__8.jpg',
                      'https://image.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-12-pro-max_2__8.jpg',
                      'https://image.cellphones.com.vn/358x/media/catalog/product/_/0/_0000_iphone-12-pro-max-nonlogo-5_1_2.jpg'
                    ]}
                  />
                </div>
              </div>
              <div className="flex flex-1 justify-between">
                <div className="w-full py-2 px-8">
                  <MainInfo product={product} />
                </div>
                <div>
                  <DeviceInfo attrs={attrs} />
                </div>
              </div>
            </div>
            <div>
              <RatingAndCommentBox />
            </div>
            <div>
              <QuestionBox />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

Phone.getInitialProps = async (context: NextPageContext & { store: Store }) => {
  const { slug } = context.query;
  try {
    const product: any = await axiosClient.get(`product/${slug}`);
    context.store.dispatch(setSelectedProduct(product));
    return {
      product
    };
  } catch (err) {
    return {
      product: undefined
    };
  }
};
export default Phone;
