import Head from 'next/head';
import { NextPage, NextPageContext } from 'next';
import { Store } from '@app/store';
import { setSelectedProduct } from '@app/slice/homeSlice';
import Breadcrumb from '@components/breadcrumb';
import axiosClient from 'utils/api';
import ProductCarousel from '@components/carousel';
import { DetailProductType } from 'types';
import DeviceInfo from '@components/product-detail/DeviceInfo';
import Divider from '@components/common/Divider';
import MainInfo from '@components/product-detail/MainInfo';
import QuestionBox from '@components/product-detail/QuestionBox';
import ReviewBox from '@components/product-detail/review/ReviewBox';
import Layout from '@components/common/Layout';
import { useCallback, useEffect, useState } from 'react';

type Props = {
  product: DetailProductType | undefined;
};

const Phone: NextPage<Props> = ({ product }) => {
  if (!product) {
    return <div>Error</div>;
  }
  const { name, slug, attrs } = product;
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [carouselRef, setCarouselRef] = useState(null);
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [images, setImages] = useState<string[]>([]);

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const handleRef = useCallback(
    (ref) => {
      setCarouselRef(ref);
    },
    [product]
  );

  // eslint-disable-next-line react-hooks/rules-of-hooks
  useEffect(() => {
    const images = product.colorOptions.reduce(
      (accumulator: string[], current) => {
        current.images.map((image) => {
          accumulator.push(image);
        });
        return accumulator;
      },
      []
    );
    setImages(images);
  }, [product]);

  return (
    <Layout>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center overflow-auto h-main bg-main">
        <div className="max-w-screen-xl w-full">
          <div className="p-4 justify-center flex-col flex gap-x-4 bg-white">
            <Breadcrumb
              breadcrumbs={[
                { value: 'Điện thoại', href: '/dien-thoai' },
                { value: name, href: slug }
              ]}
            />
            <Divider className="mt-0 mb-4" />
            <div className="flex rounded">
              <div className="flex-1 flex flex-col">
                <div className="flex flex-row">
                  <div className="detail_product_left w-[28rem] p-4 pr-0">
                    <div className="product-gallery">
                      <ProductCarousel images={images} handleRef={handleRef} />
                    </div>
                  </div>
                  <div className="mx-3 w-px bg-[#f2f2f2] shrink-0"></div>
                  <div className="flex flex-1 justify-between pt-6">
                    <div className="flex-1 py-4 px-8">
                      <MainInfo
                        product={product}
                        carouselRef={carouselRef}
                        images={images}
                      />
                    </div>
                  </div>
                </div>
                <div>
                  <ReviewBox
                    reviews={product.reviews}
                    ratingValue={product.ratingValue}
                  />
                </div>
                <div>
                  <QuestionBox />
                </div>
              </div>
              <div className="w-[345px] pr-6 pb-5">
                <DeviceInfo attrs={attrs} />
              </div>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
};

Phone.getInitialProps = async (context: NextPageContext & { store: Store }) => {
  const { slug } = context.query;
  try {
    const product: DetailProductType = await axiosClient.get(`product/${slug}`);
    context.store.dispatch(setSelectedProduct(product));
    return {
      product
    };
  } catch (err) {
    return {
      product: undefined
    };
  }
};
export default Phone;
