import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { GetServerSideProps, NextPage, NextPageContext } from 'next';
import { initializeStore, RootState, Store, useStore } from '../../app/store';
import axios from 'axios';
import { setSelectedProduct } from '../../app/slice/homeSlice';
import { useSelector } from 'react-redux';
import { useEffect } from 'react';
import Breadcrumb from '@components/breadcrumb';

type DetailProduct = {
  // _id: string
  cat: string;
  brand: string;
  slug: string;
  name: string;
  // lname: string,
  thumbnail: string;
  price: number;
  ratingValue: number;
  reviewCount: number;
  hasVariants: boolean;
  mainProduct: boolean;
  isHot: boolean;
  createdAt: Date;
  updatedAt: Date;
  linkVariants: string;
};
type IProps = {
  product: DetailProduct;
};

const Phone: NextPage<IProps> = ({ product }) => {
  const { name, slug } = product;
  return (
    <>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center overflow-auto h-main">
        <div className="max-w-screen-xl w-full">
          <div className="py-4 px-10 justify-center flex-col flex gap-x-4">
            <Breadcrumb productName={name} slug={slug} />
            <div>ncsdcn</div>
          </div>
        </div>
      </main>
    </>
  );
};

Phone.getInitialProps = async (context: NextPageContext & { store: Store }) => {
  const { slug } = context.query;
  try {
    const res = await axios.get(
      `${process.env.NEXT_PUBLIC_API_ENDPOINT}/product/${slug}`
    );
    context.store.dispatch(setSelectedProduct(res.data.product));
    return {
      product: res.data.product
    };
  } catch (err) {
    return {
      product: []
    };
  }
};
export default Phone;
