import { BellIcon, MapPinIcon, OrderIcon, UserIcon } from '@assets/icons';
import Breadcrumb from '@components/breadcrumb';
import Divider from '@components/common/Divider';
import Layout from '@components/common/Layout';
import classNames from 'classnames';
import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

type Props = any;
const AccountPage: NextPage<Props> = () => {
  return (
    <Layout>
      <Head>
        <title>Thông tin tài khoản</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center overflow-auto h-main bg-main">
        <div className="max-w-screen-xl w-full">
          <div className="p-4 justify-center flex-col flex gap-x-4">
            <Breadcrumb productName={'sấdd'} slug={'sd'} />
            <Divider className="mt-0 mb-4" />
          </div>
          <div className="flex">
            <div className="w-64 mr-4">
              <ul className="list-none m-0 p-0 text-13">
                <li>
                  <Link href={''}>
                    <a
                      className={classNames(
                        ' flex items-center py-3 px-5 text-[#4a4a4a] hover:opacity-95 hover:bg-[#ebebf0] hover:text-black rounded',
                        {
                          'bg-[#ebebf0] text-black': true
                        }
                      )}
                    >
                      <UserIcon className="text-current w-6 h-6 mr-6" />
                      <span>Thông tin tài khoản</span>
                    </a>
                  </Link>
                </li>

                <li>
                  <Link href={''}>
                    <a
                      className={classNames(
                        ' flex items-center py-3 px-5 text-[#4a4a4a] hover:opacity-95 hover:bg-[#ebebf0] hover:text-black rounded',
                        {
                          'bg-[#ebebf0] text-black': false
                        }
                      )}
                    >
                      <BellIcon className="text-current w-6 h-6 mr-6" />
                      <span>Thông báo của tôi</span>
                    </a>
                  </Link>
                </li>

                <li>
                  <Link href={''}>
                    <a
                      className={classNames(
                        ' flex items-center py-3 px-5 text-[#4a4a4a] hover:opacity-95 hover:bg-[#ebebf0] hover:text-black rounded',
                        {
                          'bg-[#ebebf0] text-black': false
                        }
                      )}
                    >
                      <OrderIcon className="text-current w-6 h-6 mr-6" />
                      <span>Quản lý đơn hàng</span>
                    </a>
                  </Link>
                </li>

                <li>
                  <Link href={''}>
                    <a
                      className={classNames(
                        ' flex items-center py-3 px-5 text-[#4a4a4a] hover:opacity-95 hover:bg-[#ebebf0] hover:text-black rounded',
                        {
                          'bg-[#ebebf0] text-black': false
                        }
                      )}
                    >
                      <MapPinIcon className="text-current w-6 h-6 mr-6" />
                      <span>Địa chỉ</span>
                    </a>
                  </Link>
                </li>
              </ul>
            </div>
            <div className="flex-1">
              <div>Thông tin tài khoản</div>
              <div className="bg-white"></div>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
};
export default AccountPage;
