import Head from 'next/head';
import { NextPage } from 'next';
import NavigationMenu from '@components/admin/navigation/NavigationMenu';
import Layout from '@components/common/Layout';
import Editor from '@components/admin/editor/Editor';
import { useEffect, useState } from 'react';
import axiosClient from '@utils/api';
import useAsyncEffect from 'use-async-effect';
import { isEmpty } from 'lodash';

type Props = any;
const AdminPage: NextPage<Props> = () => {
  const [brands, setBrands] = useState<any[]>([]);
  useAsyncEffect(async () => {
    const brands: any[] = await axiosClient.get('brands');
    setBrands(brands);
  }, []);
  return (
    <Layout admin>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-full overflow-hidden pt-14">
        <div className="h-14 fixed bg-white inset-x-0 top-0 flex shadow-sm z-[100]"></div>
        <div className="flex flex-row flex-1 overflow-hidden">
          <NavigationMenu />
          <div className="max-w-screen-xl flex-1 h-full max-h-full overflow-y-auto m-auto">
            {!isEmpty(brands) && <Editor brands={brands} />}
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default AdminPage;
