import Head from 'next/head';
import { NextPage } from 'next';
import Layout from '@components/common/Layout';
import { useState } from 'react';
import axiosClient from '@utils/api';
import { useRouter } from 'next/router';
import AuthSubmitButton from '@components/common/auth/AuthSubmitButton';
import { toast } from 'react-toastify';

type Props = any;
const ResetPassword: NextPage<Props> = () => {
  const [isLoading, setLoading] = useState(false);

  const [email, setEmail] = useState('');
  const [pass, setPass] = useState('');
  const [pass2, setPass2] = useState('');
  const router = useRouter();
  const handleResetRequest = async (e: any) => {
    e.preventDefault();
    try {
      if (pass !== pass2) {
        return toast.error('Mật khẩu không khớp');
      }
      setLoading(true);
      const result = await axiosClient.post('/auth/resetPasswordComplete', {
        email,
        newPassword: pass,
        token: router.query.token
      });
      toast.success(result);
    } catch (e) {
      console.log(e);
    } finally {
      setLoading(false);
    }
  };
  return (
    <Layout>
      <Head>
        <title>Đặt lại mật khẩu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center overflow-auto md:h-[calc(100vh-4rem)] h-[calc(100vh-3.5rem)] bg-main">
        <div className="flex flex-row flex-1">
          <div className="flex-1 h-full max-h-full overflow-y-auto">
            <div className="max-w-screen-xl m-auto h-full">
              <div className="p-4">
                <div className="flex items-center justify-between py-8 flex-col">
                  <div className="">
                    <h2 className="text-black font-medium text-xl">
                      Đặt lại mật khẩu
                    </h2>
                  </div>
                  <div className=" w-96">
                    <form onSubmit={handleResetRequest}>
                      <div className="flex items-center justify-between flex-col w-full">
                        <input
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                          type={'text'}
                          className="w-full block border h-11 placeholder:text-13 placeholder:text-gray-400 text-gray-900 rounded focus:outline-none mt-5 border-gray-300 focus:border-primary py-2 px-4"
                          autoComplete="off"
                          placeholder={'Email'}
                        />
                        <input
                          value={pass}
                          onChange={(e) => setPass(e.target.value)}
                          type={'password'}
                          className="w-full block border h-11 placeholder:text-13 placeholder:text-gray-400 text-gray-900 rounded focus:outline-none mt-5 border-gray-300 focus:border-primary py-2 px-4"
                          autoComplete="off"
                          placeholder={'Mật khẩu'}
                        />
                        <input
                          value={pass2}
                          onChange={(e) => setPass2(e.target.value)}
                          type={'password'}
                          className="w-full block border h-11 placeholder:text-13 placeholder:text-gray-400 text-gray-900 rounded focus:outline-none mt-5 border-gray-300 focus:border-primary py-2 px-4"
                          autoComplete="off"
                          placeholder={'Nhập lại mật khẩu'}
                        />
                      </div>
                      <AuthSubmitButton
                        isLoading={isLoading}
                        width="100%"
                        title="Đặt lại mật khẩu"
                      />
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default ResetPassword;
