import Head from 'next/head';
import { NextPage } from 'next';
import NavigationMenu from '@components/admin/navigation/NavigationMenu';
import Layout from '@components/common/Layout';
import CreateProductEditor from '@components/admin/editor/Editor';
import { useEffect, useState, FunctionComponent } from 'react';
import axiosClient from '@utils/api';
import useAsyncEffect from 'use-async-effect';
import { isEmpty } from 'lodash';
import { SpinnerIcon } from '@assets/icons';

type Props = any;

const Loading: FunctionComponent<any> = () => {
  return (
    <div className="h-full w-full flex items-center justify-center bg-white select-none">
      <div className="flex items-center">
        <SpinnerIcon className="animate-spin mr-2" /> Loading...
      </div>
    </div>
  );
};

const CreateProductPage: NextPage<Props> = () => {
  const [brands, setBrands] = useState<any[]>([]);
  const [isPreLoading, setPreLoading] = useState(false);

  useAsyncEffect(async () => {
    setPreLoading(true);
    const brands: any[] = await axiosClient.get('brands');
    setBrands(brands);
    // setTimeout(() => {
    setPreLoading(false);
    // }, 2000);
  }, []);

  return (
    <Layout admin>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-full overflow-hidden pt-14">
        <div className="h-14 fixed bg-white inset-x-0 top-0 flex shadow-sm z-[100]"></div>
        <div className="flex flex-row flex-1 overflow-hidden">
          <NavigationMenu />
          <div className="max-w-screen-xl flex-1 h-full max-h-full overflow-y-auto m-auto">
            {isPreLoading ? (
              <Loading />
            ) : (
              <CreateProductEditor brands={brands} method={'post'} />
            )}
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default CreateProductPage;
