import Head from 'next/head';
import { NextPage } from 'next';
import Layout from '@components/common/Layout';
import CreateProductEditor from '@components/admin/editor/Editor';
import { useState, FunctionComponent } from 'react';
import axiosClient from '@utils/api';
import useAsyncEffect from 'use-async-effect';
const NavigationMenu = dynamic(
  () => import('@components/admin/navigation/NavigationMenu'),
  {
    ssr: false
  }
);
import { SpinnerIcon } from '@assets/icons';
import dynamic from 'next/dynamic';
import { motion } from 'framer-motion';

type Props = any;

const Loading: FunctionComponent<any> = () => {
  return (
    <div className="h-full w-full flex items-center justify-center bg-transparent select-none">
      <div className="flex items-center">
        <SpinnerIcon className="animate-spin mr-2" /> Loading...
      </div>
    </div>
  );
};

const CreateProductPage: NextPage<Props> = () => {
  const [brands, setBrands] = useState<any[]>([]);
  const [isPreLoading, setPreLoading] = useState(false);

  useAsyncEffect(async () => {
    setPreLoading(true);
    const brands: any[] = await axiosClient.get('brands');
    setBrands(brands);
    setPreLoading(false);
  }, []);

  return (
    <Layout admin>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center overflow-auto md:h-[calc(100vh-4rem)] h-[calc(100vh-3.5rem)] bg-main">
        <div className="flex flex-row flex-1">
          <NavigationMenu />
          {/* <div className="max-w-screen-lg flex-1 h-full max-h-full m-auto"> */}
          <div className="flex-1 h-full max-h-full overflow-y-auto">
            <div className="max-w-screen-lg m-auto h-full">
              {isPreLoading ? (
                <Loading />
              ) : (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.3 }}
                  className="py-8"
                >
                  <h2 className="text-black font-medium text-xl px-4">
                    Add Product
                  </h2>
                  <div className="mt-4">
                    <CreateProductEditor brands={brands} method={'post'} />
                  </div>
                </motion.div>
              )}
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
};

export default CreateProductPage;
